version: '3.9'

services:
  grafana:
    image: grafana/grafana:10.1.4
    restart: always
    environment:
      GF_INSTALL_PLUGINS: "${GF_INSTALL_PLUGINS}"
#      GF_DEFAULT_INSTANCE_NAME: "${GF_DEFAULT_INSTANCE_NAME}"
#      GF_DEFAULT_APP_MODE: "${GF_DEFAULT_APP_MODE}"
#      GF_SERVER_ROOT_URL: "${GRAFANA_FQDN}"
#      GF_DATABASE_TYPE: "${GF_DATABASE_TYPE}"
#      GF_DATABASE_HOST: "${GF_DATABASE_HOST}"
#      GF_DATABASE_NAME: "${GF_DATABASE_NAME}"
#      GF_DATABASE_USER: "${GF_DATABASE_USER}"
#      GF_DATABASE_PASSWORD: "${GF_DATABASE_PASSWORD}"
#      GF_DATABASE_URL: "${GF_DATABASE_URL}"
#      GF_SECURITY_ADMIN_USER: "${GF_SECURITY_ADMIN_USER}"
#      GF_SECURITY_ADMIN_PASSWORD: "${GF_SECURITY_ADMIN_PASSWORD}"
#      GF_USERS_ALLOW_SIGN_UP: "${GF_USERS_ALLOW_SIGN_UP}"
#      GF_USERS_ALLOW_ORG_CREATE: "${GF_USERS_ALLOW_ORG_CREATE}"
#      GF_USER_VERIFY_EMAIL_ENABLED: "${GF_USER_VERIFY_EMAIL_ENABLED}"
#      GF_USER_DEFAULT_THEME: "${GF_USER_DEFAULT_THEME}"
#      GF_SMTP_ENABLED: "${GF_SMTP_ENABLED}"
#      GF_SMTP_HOST: "${GF_SMTP_HOST}"
#      GF_SMTP_USER: "${GF_SMTP_USER}"
#      GF_SMTP_PASSWORD: "${GF_SMTP_PASSWORD}"
#      GF_SMTP_FROM_ADDRESS: "${GF_SMTP_FROM_ADDRESS}"
#      GF_SMTP_FROM_NAME: "${GF_SMTP_FROM_NAME}"
    volumes:
      - ./Data:/var/lib/grafana
    user: "${USERID}"
    networks:
      - traefik-proxy
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.${PROJECT_IDENTIFIER}.tls=true'
      - 'traefik.http.routers.${PROJECT_IDENTIFIER}.entrypoints=https'
      - 'traefik.http.routers.${PROJECT_IDENTIFIER}.rule=Host(`${GRAFANA_FQDN}`)'
      #- 'traefik.http.routers.${PROJECT_IDENTIFIER}.middlewares=middlewares-authentik@file'
      - 'traefik.http.routers.${PROJECT_IDENTIFIER}.service=${PROJECT_IDENTIFIER}'
      - 'traefik.http.services.${PROJECT_IDENTIFIER}.loadbalancer.server.port=3000'

networks:
  traefik-proxy:
    name: traefik-proxy
    driver: bridge
    external: true
